### ISSUE TITLE
Add rich menu

### ISSUE THREAD

**Issue by dlemstra** [dlemstra/line-bot-sdk-dotnet#3]
https://developers.line.me/en/docs/messaging-api/reference/#rich-menu
https://developers.line.me/en/docs/messaging-api/reference/#rich-menu-structure

This issue is split into the following issues:

- [x] Add RichMenu class.
- [x] Add CreateRichMenu to LineBot.
- [x] Add ActionConverter (#40)
- [x] Add SetRichMenuImage to LineBot (#22)
- [x] Add GetRichMenuImage to LineBot (#23)
- [x] Add RichMenuResponse (#24)
- [x] Add GetRichMenus to LineBot (#25)
- [x] Add GetRichMenu to LineBot (#26)
- [x] Add DeleteRichMenu to LineBot (#27)
- [x] Add SetDefaultRichMenu to LineBot (#28)
- [x] Add GetDefaultRichMenu to LineBot (#29)
- [x] Add DeleteDefaultRichMenu to LineBot (#30)
- [x] Add SetUserRichMenu to LineBot (#31)
- [x] Add GetUserRichMenu to LineBot (#32)
- [x] Add DeleteUserRichMenu to LineBot (#33)

**Comment by Ben67366** [comment]
I'm trying to make change on this issue.
I'm confused on making the method to upload the rich menu image.
Is this good to take byte[] as parameter?

```
        /// <summary>
        /// Uploads and attaches an image to a rich menu.
        /// </summary>
        /// <param name="richMenuId">The target rich menu id.</param>
        /// <param name="richMenuImage">The rich menu Image.</param>
        public async void UploadRichMenuImage(string richMenuId, byte[] richMenuImage)
        {
            Guard.NotNullOrEmpty(nameof(richMenuId), richMenuId);
            Guard.NotNull(nameof(richMenuImage), richMenuImage);

            var content = CreateImageContent(richMenuImage);
            HttpResponseMessage response = await _client.PostAsync($"richmenu/" + richMenuId + "/content", content);
            await response.CheckResult();
        }
```


```
        private static MultipartFormDataContent CreateImageContent(byte[] paramFileBytes)
        {
            MultipartFormDataContent form = new MultipartFormDataContent();

            form.Headers.Add("Content-Type", "image/jpeg");
            form.Add(new ByteArrayContent(paramFileBytes), "richMenu", "image.jpg");

            return form;
        }
```

**Comment by Ben67366** [comment]
Thanks.
Will try to do this step by steps.

**Comment by dlemstra** [comment]
@Ben67366 Cool, and thanks for helping me with this again 👍

**Comment by Ben67366** [comment]
I'd like to.
And I'm not good at code / project structures.
This helped me alot. : )
